language: python
python:
  - "2.6"
  - "2.7"
env:
  -
  - MIGRATIONS=yes
  - SEARCH=elasticsearch
  - DB=mysql
before_install:
  - if [ $SEARCH == 'elasticsearch' ]; then sudo service elasticsearch start; sleep 3; fi
install:
  - pip install . --no-deps
  - pip install --use-mirrors --no-deps -r test_mc_project/requirements.txt
  - if [ $TRAVIS_PYTHON_VERSION == '2.6' ]; then pip install --use-mirrors --no-deps importlib ordereddict; fi
  - if [ $MIGRATIONS == 'yes' ]; then pip install --use-mirrors --no-deps south; fi
  - if [ $SEARCH == 'elasticsearch' ]; then pip install --use-mirrors --no-deps pyelasticsearch; fi
  - if [ $DB == 'mysql' ]; then pip install --use-mirrors --no-deps mysql-python; fi
before_script:
  - if [ $DB == 'mysql' ]; then mysql -e 'CREATE DATABASE mirocommunity_test;'; fi
script:
  - cd test_mc_project
  - ./manage.py test localtv.tests.unit --verbosity=2
  - ./manage.py test localtv.tests.functional --verbosity=2
  - ./manage.py test localtv.tests.integration --verbosity=2
  - ./manage.py test localtv.tests.legacy --verbosity=2
  - ./manage.py test localtv.contrib.contests --verbosity=2
